server:
  port: 8061
  
eureka:  instance:    hostname: localhost:8061     #设置Eureka服务器的名字
    
  client:    register-with-eureka: false   #设置本项目不需要注册到Eureka服务器中
    fetch-registry: false         #不需要检索服务
    service-url:      defaultZone: http://localhost:8062/eureka/  #设置Eureka Client（provider）注册服务的url