server:
  port: 8081
  
mybatis:  type-aliases-package: com.springcloud.entity  #设置Mybatis实体类的位置
  mapper-locations:                             #设置Mybatis的Mapper.xml文件的位置  - classpath:mapper/*.xml
  
spring:  application:    name: springcloud-01-dept-provider  #当前项目的名字
  datasource:                           #设置数据源的信息    type: com.alibaba.druid.pool.DruidDataSource  #设置数据库连接池的类型
    driver-class-name: org.gjt.mm.mysql.Driver    #设置数据库驱动
    url: jdbc:mysql://127.0.0.1:3306/zgc
    username: root
    password: root
    dbcp2:      min-idle: 5                   #设置最小连接数据
      initial-size: 5               #设置当前数据库连接池启动时，创建的连接数
      max-total: 10                 #设置最大连接数
      max-wait-millis: 2000         #设置最大等待时间
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka/,http://localhost:8062/eureka/     #设置Eurakafu服务器的url
    